#--- Installing ansible ----

- name: set up ansible
  hosts: ansible
  tasks: 
    - name: ensure nginx is at the latest version
      become: true
      dnf:
        name: ansible-core
        state: latest