[all:children]
ansible
nginx
ubuntu

[ansible]
centos@centos-std3-2-4-35gb ansible_host=212.233.74.9

[nginx]
centos@centos-std3-2-4-15gb  ansible_host=212.233.73.252

[ubuntu]
ubuntu@ubuntu-std2-4-4-10gb ansible_host=212.233.72.247